REFRESH sdbackend.sd_account_action_log;
REFRESH sdbackend.sd_ad_coin;
REFRESH sdbackend.sd_ad_coin_log;
REFRESH sdbackend.sd_ad_device_log;
REFRESH sdbackend.sd_ad_oper_log;
REFRESH sdbackend.sd_ad_plan_bgs;
REFRESH sdbackend.sd_ad_plan_log;
REFRESH sdbackend.sd_ad_plan_page;
REFRESH sdbackend.sd_ad_plan_self_users;
REFRESH sdbackend.sd_ad_plans;
REFRESH sdbackend.sd_ad_soft_plans;
REFRESH sdbackend.sd_ad_visit_count;
REFRESH sdbackend.sd_agent_finance;
REFRESH sdbackend.sd_agent_rate_switch;
REFRESH sdbackend.sd_allocation_strategy;
REFRESH sdbackend.sd_app_approval;
REFRESH sdbackend.sd_app_home_window;
REFRESH sdbackend.sd_app_menu_role;
REFRESH sdbackend.sd_app_menu_role_nature;
REFRESH sdbackend.sd_app_menu_sort;
REFRESH sdbackend.sd_app_menu_user_view_role;
REFRESH sdbackend.sd_app_menus;
REFRESH sdbackend.sd_app_menus_module;
REFRESH sdbackend.sd_app_role_feature_bind;
REFRESH sdbackend.sd_app_role_feature_bind_menu;
REFRESH sdbackend.sd_app_role_feature_setting;
REFRESH sdbackend.sd_app_role_view_menu;
REFRESH sdbackend.sd_app_user_feature_auth;
REFRESH sdbackend.sd_app_visit_log;
REFRESH sdbackend.sd_app_visitors;
REFRESH sdbackend.sd_approval;
REFRESH sdbackend.sd_approval_log;
REFRESH sdbackend.sd_approval_records;
REFRESH sdbackend.sd_ass_approval_record;
REFRESH sdbackend.sd_ass_repair_record;
REFRESH sdbackend.sd_ass_repair_users;
REFRESH sdbackend.sd_backend_battery_bill;
REFRESH sdbackend.sd_backend_equip_bill;
REFRESH sdbackend.sd_backend_image;
REFRESH sdbackend.sd_backend_merchant_bill_account_daily;
REFRESH sdbackend.sd_backend_merchant_station_bill;
REFRESH sdbackend.sd_backend_pause_fee_apply;
REFRESH sdbackend.sd_backend_pause_fee_remind_log;
REFRESH sdbackend.sd_backend_refund_apply;
REFRESH sdbackend.sd_backend_refund_apply_alarm_log;
REFRESH sdbackend.sd_backend_sale_bill_account_daily;
REFRESH sdbackend.sd_backend_shop_bill;
REFRESH sdbackend.sd_backend_shop_bill_extend;
REFRESH sdbackend.sd_backend_shop_equip_count;
REFRESH sdbackend.sd_backend_shop_staff_bill;
REFRESH sdbackend.sd_backend_station_bill;
REFRESH sdbackend.sd_backend_station_bill_extend;
REFRESH sdbackend.sd_backend_station_bill_sum;
REFRESH sdbackend.sd_backend_user_bill_account_daily;
REFRESH sdbackend.sd_backend_user_shop_bill;
REFRESH sdbackend.sd_bank_list;
REFRESH sdbackend.sd_battery_apply;
REFRESH sdbackend.sd_battery_flow_log;
REFRESH sdbackend.sd_battery_recall_log;
REFRESH sdbackend.sd_battery_trans_log;
REFRESH sdbackend.sd_college_course;
REFRESH sdbackend.sd_college_course_bind_group;
REFRESH sdbackend.sd_college_course_group;
REFRESH sdbackend.sd_college_user_course;
REFRESH sdbackend.sd_contract_again_debug_order;
REFRESH sdbackend.sd_contract_again_sign_order;
REFRESH sdbackend.sd_corp_department;
REFRESH sdbackend.sd_corp_department_user;
REFRESH sdbackend.sd_corp_user;
REFRESH sdbackend.sd_crm_sync_account_error_log;
REFRESH sdbackend.sd_cuser_oper_log;
REFRESH sdbackend.sd_custom_services_setting;
REFRESH sdbackend.sd_daily_income_rate;
REFRESH sdbackend.sd_device_change_bind_log;
REFRESH sdbackend.sd_device_flow_statistic_days;
REFRESH sdbackend.sd_device_manage_data;
REFRESH sdbackend.sd_device_offline_log;
REFRESH sdbackend.sd_device_oper_record;
REFRESH sdbackend.sd_device_oper_record_detail;
REFRESH sdbackend.sd_device_update;
REFRESH sdbackend.sd_device_update_list;
REFRESH sdbackend.sd_device_version_data;
REFRESH sdbackend.sd_equip_group;
REFRESH sdbackend.sd_equip_state;
REFRESH sdbackend.sd_equip_version;
REFRESH sdbackend.sd_error_notify_log;
REFRESH sdbackend.sd_exception_log;
REFRESH sdbackend.sd_express;
REFRESH sdbackend.sd_express_config;
REFRESH sdbackend.sd_face_auth_order;
REFRESH sdbackend.sd_finance_report_days;
REFRESH sdbackend.sd_finance_sale_order_contact;
REFRESH sdbackend.sd_finance_sale_order_contact_tpl;
REFRESH sdbackend.sd_finance_sale_order_info;
REFRESH sdbackend.sd_financeproval_flow;
REFRESH sdbackend.sd_freeze_detail_ptg;
REFRESH sdbackend.sd_freeze_log;
REFRESH sdbackend.sd_freeze_strategy;
REFRESH sdbackend.sd_menus;
REFRESH sdbackend.sd_merchant_bind;
REFRESH sdbackend.sd_merchant_bind_log;
REFRESH sdbackend.sd_merchant_servicer_relation;
REFRESH sdbackend.sd_ocr_verification;
REFRESH sdbackend.sd_official_msg;
REFRESH sdbackend.sd_official_msg_img;
REFRESH sdbackend.sd_official_msg_reply;
REFRESH sdbackend.sd_offline_device_statistics;
REFRESH sdbackend.sd_offset_payment;
REFRESH sdbackend.sd_oper_record;
REFRESH sdbackend.sd_order_count;
REFRESH sdbackend.sd_path;
REFRESH sdbackend.sd_permission_path;
REFRESH sdbackend.sd_permissions;
REFRESH sdbackend.sd_qrcode_bind_log;
REFRESH sdbackend.sd_role_menu;
REFRESH sdbackend.sd_role_permission;
REFRESH sdbackend.sd_roles_soudian;
REFRESH sdbackend.sd_sale_manager_bind;
REFRESH sdbackend.sd_sale_manager_relation;
REFRESH sdbackend.sd_sale_record;
REFRESH sdbackend.sd_sale_record_item;
REFRESH sdbackend.sd_shop_count;
REFRESH sdbackend.sd_shop_repair_geo_logs;
REFRESH sdbackend.sd_slot_count;
REFRESH sdbackend.sd_source_bind;
REFRESH sdbackend.sd_stock;
REFRESH sdbackend.sd_stock_detail;
REFRESH sdbackend.sd_stock_equip;
REFRESH sdbackend.sd_sys_oper_log;
REFRESH sdbackend.sd_tv_bulletin;
REFRESH sdbackend.sd_tv_config;
REFRESH sdbackend.sd_user_active;
REFRESH sdbackend.sd_user_additional_info;
REFRESH sdbackend.sd_user_bank;
REFRESH sdbackend.sd_user_delivery_addr;
REFRESH sdbackend.sd_user_equip_bind;
REFRESH sdbackend.sd_user_identify_info;
REFRESH sdbackend.sd_user_member_bind;
REFRESH sdbackend.sd_user_permission;
REFRESH sdbackend.sd_user_record_check;
REFRESH sdbackend.sd_user_relation;
REFRESH sdbackend.sd_user_role;
REFRESH sdbackend.sd_user_setting;
REFRESH sdbackend.sd_user_shop_bind;
REFRESH sdbackend.sd_user_shop_bind_log;
REFRESH sdbackend.sd_users;
REFRESH sdbackend.sd_users_account;
REFRESH sdbackend.sd_users_ext;
REFRESH sdbackend.sd_wechat;
REFRESH sdbackend.sd_withdraw_receiver;
REFRESH sdbackend.sd_yunzhanghu_sign_logs;

upsert into impala_sdbackend.sd_account_action_log
SELECT * FROM sdbackend.sd_account_action_log;

upsert into impala_sdbackend.sd_ad_coin
SELECT * FROM sdbackend.sd_ad_coin;

upsert into impala_sdbackend.sd_ad_coin_log
SELECT * FROM sdbackend.sd_ad_coin_log;

upsert into impala_sdbackend.sd_ad_device_log
SELECT * FROM sdbackend.sd_ad_device_log;

upsert into impala_sdbackend.sd_ad_oper_log
SELECT * FROM sdbackend.sd_ad_oper_log;

upsert into impala_sdbackend.sd_ad_plan_bgs
SELECT * FROM sdbackend.sd_ad_plan_bgs;

upsert into impala_sdbackend.sd_ad_plan_log
SELECT * FROM sdbackend.sd_ad_plan_log;

upsert into impala_sdbackend.sd_ad_plan_page
SELECT * FROM sdbackend.sd_ad_plan_page;

upsert into impala_sdbackend.sd_ad_plan_self_users
SELECT * FROM sdbackend.sd_ad_plan_self_users;

upsert into impala_sdbackend.sd_ad_plans
SELECT * FROM sdbackend.sd_ad_plans;

upsert into impala_sdbackend.sd_ad_soft_plans
SELECT * FROM sdbackend.sd_ad_soft_plans;

upsert into impala_sdbackend.sd_ad_visit_count
SELECT * FROM sdbackend.sd_ad_visit_count;

upsert into impala_sdbackend.sd_agent_finance
SELECT * FROM sdbackend.sd_agent_finance;

upsert into impala_sdbackend.sd_agent_rate_switch
SELECT * FROM sdbackend.sd_agent_rate_switch;

upsert into impala_sdbackend.sd_allocation_strategy
SELECT * FROM sdbackend.sd_allocation_strategy;

upsert into impala_sdbackend.sd_app_approval
SELECT * FROM sdbackend.sd_app_approval;

upsert into impala_sdbackend.sd_app_home_window
SELECT * FROM sdbackend.sd_app_home_window;

upsert into impala_sdbackend.sd_app_menu_role
SELECT * FROM sdbackend.sd_app_menu_role;

upsert into impala_sdbackend.sd_app_menu_role_nature
SELECT * FROM sdbackend.sd_app_menu_role_nature;

upsert into impala_sdbackend.sd_app_menu_sort
SELECT * FROM sdbackend.sd_app_menu_sort;

upsert into impala_sdbackend.sd_app_menu_user_view_role
SELECT * FROM sdbackend.sd_app_menu_user_view_role;

upsert into impala_sdbackend.sd_app_menus
SELECT * FROM sdbackend.sd_app_menus;

upsert into impala_sdbackend.sd_app_menus_module
SELECT * FROM sdbackend.sd_app_menus_module;

upsert into impala_sdbackend.sd_app_role_feature_bind
SELECT * FROM sdbackend.sd_app_role_feature_bind;

upsert into impala_sdbackend.sd_app_role_feature_bind_menu
SELECT * FROM sdbackend.sd_app_role_feature_bind_menu;

upsert into impala_sdbackend.sd_app_role_feature_setting
SELECT * FROM sdbackend.sd_app_role_feature_setting;

upsert into impala_sdbackend.sd_app_role_view_menu
SELECT * FROM sdbackend.sd_app_role_view_menu;

upsert into impala_sdbackend.sd_app_user_feature_auth
SELECT * FROM sdbackend.sd_app_user_feature_auth;

upsert into impala_sdbackend.sd_app_visit_log
SELECT * FROM sdbackend.sd_app_visit_log;

upsert into impala_sdbackend.sd_app_visitors
SELECT * FROM sdbackend.sd_app_visitors;

upsert into impala_sdbackend.sd_approval
SELECT * FROM sdbackend.sd_approval;

upsert into impala_sdbackend.sd_approval_log
SELECT * FROM sdbackend.sd_approval_log;

upsert into impala_sdbackend.sd_approval_records
SELECT * FROM sdbackend.sd_approval_records;

upsert into impala_sdbackend.sd_ass_approval_record
SELECT * FROM sdbackend.sd_ass_approval_record;

upsert into impala_sdbackend.sd_ass_repair_record
SELECT * FROM sdbackend.sd_ass_repair_record;

upsert into impala_sdbackend.sd_ass_repair_users
SELECT * FROM sdbackend.sd_ass_repair_users;

upsert into impala_sdbackend.sd_backend_battery_bill
SELECT * FROM sdbackend.sd_backend_battery_bill;

upsert into impala_sdbackend.sd_backend_equip_bill
SELECT * FROM sdbackend.sd_backend_equip_bill;

upsert into impala_sdbackend.sd_backend_image
SELECT * FROM sdbackend.sd_backend_image;

upsert into impala_sdbackend.sd_backend_merchant_bill_account_daily
SELECT * FROM sdbackend.sd_backend_merchant_bill_account_daily;

upsert into impala_sdbackend.sd_backend_merchant_station_bill
SELECT * FROM sdbackend.sd_backend_merchant_station_bill;

upsert into impala_sdbackend.sd_backend_pause_fee_apply
SELECT * FROM sdbackend.sd_backend_pause_fee_apply;

upsert into impala_sdbackend.sd_backend_pause_fee_remind_log
SELECT * FROM sdbackend.sd_backend_pause_fee_remind_log;

upsert into impala_sdbackend.sd_backend_refund_apply
SELECT * FROM sdbackend.sd_backend_refund_apply;

upsert into impala_sdbackend.sd_backend_refund_apply_alarm_log
SELECT * FROM sdbackend.sd_backend_refund_apply_alarm_log;

upsert into impala_sdbackend.sd_backend_sale_bill_account_daily
SELECT * FROM sdbackend.sd_backend_sale_bill_account_daily;

upsert into impala_sdbackend.sd_backend_shop_bill
SELECT * FROM sdbackend.sd_backend_shop_bill;

upsert into impala_sdbackend.sd_backend_shop_bill_extend
SELECT * FROM sdbackend.sd_backend_shop_bill_extend;

upsert into impala_sdbackend.sd_backend_shop_equip_count
SELECT * FROM sdbackend.sd_backend_shop_equip_count;

upsert into impala_sdbackend.sd_backend_shop_staff_bill
SELECT * FROM sdbackend.sd_backend_shop_staff_bill;

upsert into impala_sdbackend.sd_backend_station_bill
SELECT * FROM sdbackend.sd_backend_station_bill;

upsert into impala_sdbackend.sd_backend_station_bill_extend
SELECT * FROM sdbackend.sd_backend_station_bill_extend;

upsert into impala_sdbackend.sd_backend_station_bill_sum
SELECT * FROM sdbackend.sd_backend_station_bill_sum;

upsert into impala_sdbackend.sd_backend_user_bill_account_daily
SELECT * FROM sdbackend.sd_backend_user_bill_account_daily;

upsert into impala_sdbackend.sd_backend_user_shop_bill
SELECT * FROM sdbackend.sd_backend_user_shop_bill;

upsert into impala_sdbackend.sd_bank_list
SELECT * FROM sdbackend.sd_bank_list;

upsert into impala_sdbackend.sd_battery_apply
SELECT * FROM sdbackend.sd_battery_apply;

upsert into impala_sdbackend.sd_battery_flow_log
SELECT * FROM sdbackend.sd_battery_flow_log;

upsert into impala_sdbackend.sd_battery_recall_log
SELECT * FROM sdbackend.sd_battery_recall_log;

upsert into impala_sdbackend.sd_battery_trans_log
SELECT * FROM sdbackend.sd_battery_trans_log;

upsert into impala_sdbackend.sd_college_course
SELECT * FROM sdbackend.sd_college_course;

upsert into impala_sdbackend.sd_college_course_bind_group
SELECT * FROM sdbackend.sd_college_course_bind_group;

upsert into impala_sdbackend.sd_college_course_group
SELECT * FROM sdbackend.sd_college_course_group;

upsert into impala_sdbackend.sd_college_user_course
SELECT * FROM sdbackend.sd_college_user_course;

upsert into impala_sdbackend.sd_contract_again_debug_order
SELECT * FROM sdbackend.sd_contract_again_debug_order;

upsert into impala_sdbackend.sd_contract_again_sign_order
SELECT * FROM sdbackend.sd_contract_again_sign_order;

upsert into impala_sdbackend.sd_corp_department
SELECT * FROM sdbackend.sd_corp_department;

upsert into impala_sdbackend.sd_corp_department_user
SELECT * FROM sdbackend.sd_corp_department_user;

upsert into impala_sdbackend.sd_corp_user
SELECT * FROM sdbackend.sd_corp_user;

upsert into impala_sdbackend.sd_crm_sync_account_error_log
SELECT * FROM sdbackend.sd_crm_sync_account_error_log;

upsert into impala_sdbackend.sd_cuser_oper_log
SELECT * FROM sdbackend.sd_cuser_oper_log;

upsert into impala_sdbackend.sd_custom_services_setting
SELECT * FROM sdbackend.sd_custom_services_setting;

upsert into impala_sdbackend.sd_daily_income_rate
SELECT * FROM sdbackend.sd_daily_income_rate;

upsert into impala_sdbackend.sd_device_change_bind_log
SELECT * FROM sdbackend.sd_device_change_bind_log;

upsert into impala_sdbackend.sd_device_flow_statistic_days
SELECT * FROM sdbackend.sd_device_flow_statistic_days;

upsert into impala_sdbackend.sd_device_manage_data
SELECT * FROM sdbackend.sd_device_manage_data;

upsert into impala_sdbackend.sd_device_offline_log
SELECT * FROM sdbackend.sd_device_offline_log;

upsert into impala_sdbackend.sd_device_oper_record
SELECT * FROM sdbackend.sd_device_oper_record;

upsert into impala_sdbackend.sd_device_oper_record_detail
SELECT * FROM sdbackend.sd_device_oper_record_detail;

upsert into impala_sdbackend.sd_device_update
SELECT * FROM sdbackend.sd_device_update;

upsert into impala_sdbackend.sd_device_update_list
SELECT * FROM sdbackend.sd_device_update_list;

upsert into impala_sdbackend.sd_device_version_data
SELECT * FROM sdbackend.sd_device_version_data;

upsert into impala_sdbackend.sd_equip_group
SELECT * FROM sdbackend.sd_equip_group;

upsert into impala_sdbackend.sd_equip_state
SELECT * FROM sdbackend.sd_equip_state;

upsert into impala_sdbackend.sd_equip_version
SELECT * FROM sdbackend.sd_equip_version;

upsert into impala_sdbackend.sd_error_notify_log
SELECT * FROM sdbackend.sd_error_notify_log;

upsert into impala_sdbackend.sd_exception_log
SELECT * FROM sdbackend.sd_exception_log;

upsert into impala_sdbackend.sd_express
SELECT * FROM sdbackend.sd_express;

upsert into impala_sdbackend.sd_express_config
SELECT * FROM sdbackend.sd_express_config;

upsert into impala_sdbackend.sd_finance_report_days
SELECT * FROM sdbackend.sd_finance_report_days;

upsert into impala_sdbackend.sd_finance_sale_order_contact
SELECT * FROM sdbackend.sd_finance_sale_order_contact;

upsert into impala_sdbackend.sd_finance_sale_order_contact_tpl
SELECT * FROM sdbackend.sd_finance_sale_order_contact_tpl;

upsert into impala_sdbackend.sd_finance_sale_order_info
SELECT * FROM sdbackend.sd_finance_sale_order_info;

upsert into impala_sdbackend.sd_financeproval_flow
SELECT * FROM sdbackend.sd_financeproval_flow;

upsert into impala_sdbackend.sd_freeze_detail_ptg
SELECT * FROM sdbackend.sd_freeze_detail_ptg;

upsert into impala_sdbackend.sd_freeze_log
SELECT * FROM sdbackend.sd_freeze_log;

upsert into impala_sdbackend.sd_freeze_strategy
SELECT * FROM sdbackend.sd_freeze_strategy;

upsert into impala_sdbackend.sd_menus
SELECT * FROM sdbackend.sd_menus;

upsert into impala_sdbackend.sd_merchant_bind
SELECT * FROM sdbackend.sd_merchant_bind;

upsert into impala_sdbackend.sd_merchant_bind_log
SELECT * FROM sdbackend.sd_merchant_bind_log;

upsert into impala_sdbackend.sd_merchant_servicer_relation
SELECT * FROM sdbackend.sd_merchant_servicer_relation;

upsert into impala_sdbackend.sd_ocr_verification
SELECT * FROM sdbackend.sd_ocr_verification;

upsert into impala_sdbackend.sd_official_msg
SELECT * FROM sdbackend.sd_official_msg;

upsert into impala_sdbackend.sd_official_msg_img
SELECT * FROM sdbackend.sd_official_msg_img;

upsert into impala_sdbackend.sd_official_msg_reply
SELECT * FROM sdbackend.sd_official_msg_reply;

upsert into impala_sdbackend.sd_offline_device_statistics
SELECT * FROM sdbackend.sd_offline_device_statistics;

upsert into impala_sdbackend.sd_offset_payment
SELECT * FROM sdbackend.sd_offset_payment;

upsert into impala_sdbackend.sd_oper_record
SELECT * FROM sdbackend.sd_oper_record;

upsert into impala_sdbackend.sd_order_count
SELECT * FROM sdbackend.sd_order_count;

upsert into impala_sdbackend.sd_path
SELECT * FROM sdbackend.sd_path;

upsert into impala_sdbackend.sd_permission_path
SELECT * FROM sdbackend.sd_permission_path;

upsert into impala_sdbackend.sd_permissions
SELECT * FROM sdbackend.sd_permissions;

upsert into impala_sdbackend.sd_qrcode_bind_log
SELECT * FROM sdbackend.sd_qrcode_bind_log;

upsert into impala_sdbackend.sd_role_menu
SELECT * FROM sdbackend.sd_role_menu;

upsert into impala_sdbackend.sd_role_permission
SELECT * FROM sdbackend.sd_role_permission;

upsert into impala_sdbackend.sd_roles_soudian
SELECT * FROM sdbackend.sd_roles_soudian;

upsert into impala_sdbackend.sd_sale_manager_bind
SELECT * FROM sdbackend.sd_sale_manager_bind;

upsert into impala_sdbackend.sd_sale_manager_relation
SELECT * FROM sdbackend.sd_sale_manager_relation;

upsert into impala_sdbackend.sd_sale_record
SELECT * FROM sdbackend.sd_sale_record;

upsert into impala_sdbackend.sd_sale_record_item
SELECT * FROM sdbackend.sd_sale_record_item;

upsert into impala_sdbackend.sd_shop_count
SELECT * FROM sdbackend.sd_shop_count;

upsert into impala_sdbackend.sd_shop_repair_geo_logs
SELECT * FROM sdbackend.sd_shop_repair_geo_logs;

upsert into impala_sdbackend.sd_slot_count
SELECT * FROM sdbackend.sd_slot_count;

upsert into impala_sdbackend.sd_source_bind
SELECT * FROM sdbackend.sd_source_bind;

upsert into impala_sdbackend.sd_stock
SELECT * FROM sdbackend.sd_stock;

upsert into impala_sdbackend.sd_stock_equip
SELECT * FROM sdbackend.sd_stock_equip;

upsert into impala_sdbackend.sd_sys_oper_log
SELECT * FROM sdbackend.sd_sys_oper_log;

upsert into impala_sdbackend.sd_tv_bulletin
SELECT * FROM sdbackend.sd_tv_bulletin;

upsert into impala_sdbackend.sd_tv_config
SELECT * FROM sdbackend.sd_tv_config;

upsert into impala_sdbackend.sd_user_active
SELECT * FROM sdbackend.sd_user_active;

upsert into impala_sdbackend.sd_user_additional_info
SELECT * FROM sdbackend.sd_user_additional_info;

upsert into impala_sdbackend.sd_user_bank
SELECT * FROM sdbackend.sd_user_bank;

upsert into impala_sdbackend.sd_user_delivery_addr
SELECT * FROM sdbackend.sd_user_delivery_addr;

upsert into impala_sdbackend.sd_user_equip_bind
SELECT * FROM sdbackend.sd_user_equip_bind;

upsert into impala_sdbackend.sd_user_member_bind
SELECT * FROM sdbackend.sd_user_member_bind;

upsert into impala_sdbackend.sd_user_permission
SELECT * FROM sdbackend.sd_user_permission;

upsert into impala_sdbackend.sd_user_relation
SELECT * FROM sdbackend.sd_user_relation;

upsert into impala_sdbackend.sd_user_role
SELECT * FROM sdbackend.sd_user_role;

upsert into impala_sdbackend.sd_user_setting
SELECT * FROM sdbackend.sd_user_setting;

upsert into impala_sdbackend.sd_user_shop_bind
SELECT * FROM sdbackend.sd_user_shop_bind;

upsert into impala_sdbackend.sd_user_shop_bind_log
SELECT * FROM sdbackend.sd_user_shop_bind_log;

upsert into impala_sdbackend.sd_users
SELECT * FROM sdbackend.sd_users;

upsert into impala_sdbackend.sd_users_account
SELECT * FROM sdbackend.sd_users_account;

upsert into impala_sdbackend.sd_users_ext
SELECT * FROM sdbackend.sd_users_ext;

upsert into impala_sdbackend.sd_wechat
SELECT * FROM sdbackend.sd_wechat;

upsert into impala_sdbackend.sd_withdraw_receiver
SELECT * FROM sdbackend.sd_withdraw_receiver;

upsert into impala_sdbackend.sd_yunzhanghu_sign_logs
SELECT * FROM sdbackend.sd_yunzhanghu_sign_logs;

upsert into impala_sdbackend.sd_face_auth_order
SELECT sharing_seq, db_seq, tb_seq, id, user_id, open_order_id, source, name, id_card_no, face_id, if(length(face_image)>65536,"",face_image), origin, result, status, create_at, update_at FROM sdbackend.sd_face_auth_order;


upsert into impala_sdbackend.sd_stock_detail
SELECT sharing_seq, db_seq, tb_seq, stock_detail_id, stock_id, goods_type, goods_color, goods_material, goods_count, remark, created_at, updated_at, line_type, stock_type, receive_uid, if(length(numbers)>65536,"",numbers) FROM sdbackend.sd_stock_detail;


upsert into impala_sdbackend.sd_user_identify_info
SELECT sharing_seq, db_seq, tb_seq, id, user_id, re_user_name, id_card_no, birthday, id_card_renewal, id_card_indate, face_auth_status, if(length(face_image)>65536,"",face_image), create_at, update_at FROM sdbackend.sd_user_identify_info;


set max_row_size=16777216;
upsert into impala_sdbackend.sd_user_record_check
SELECT sharing_seq, db_seq, tb_seq, user_record_check_id, check_date, origin, source, payment_source, sd_amount, excel_amount, create_at, update_at, status, type, check_date_b, remark, if(length(sd_has)>65536,"",sd_has), if(length(excel_has)>65536,"",excel_has), date_type, sd_amount_handling_fee, excel_amount_handling_fee FROM sdbackend.sd_user_record_check;
